# Generated by Django 5.0.7 on 2026-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='license/'),
        ),
    ]
