# Generated by Django 5.0.7 on 2026-02-13 12:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Oil Change', 'Oil Change'), ('Engine Repair', 'Engine Repair'), ('AC Service', 'AC Service'), ('Brake Service', 'Brake Service'), ('Battery Service', 'Battery Service'), ('Tire Service', 'Tire Service')], max_length=78, null=True),
        ),
    ]
