# Generated by Django 5.0.7 on 2026-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_workshop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
