# Generated by Django 5.0.7 on 2026-02-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_workshop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='time',
            new_name='closing_time',
        ),
        migrations.AddField(
            model_name='workshop',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
