# Generated by Django 5.0.7 on 2026-02-14 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_time_workshop_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('rc', models.FileField(blank=True, null=True, upload_to='rc/')),
                ('insurance', models.FileField(blank=True, null=True, upload_to='insurance/')),
                ('pollution', models.FileField(blank=True, null=True, upload_to='pollution/')),
                ('userd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
