# Generated by Django 5.0.7 on 2026-02-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_workshop_is_approved_vehicleregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('userd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicleregistration')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
                ('userd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workshop')),
            ],
        ),
    ]
