# Generated by Django 5.0.7 on 2026-02-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
    ]
