# Generated by Django 5.0.7 on 2026-02-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_booking_service_booking_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateField(),
        ),
    ]
