# Generated by Django 6.0.2 on 2026-02-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
                ('userd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workshop')),
            ],
        ),
    ]
